Fix imagination on death
DarkflameUniverse/DarkflameServer pull request #1006
Opened 2023-03-01 09:35 UTC by EmosewaMC

Fixes #1005 

Properly implements losing half you imagination, rounded up to the nearest 10.  

Tested that imagination is lost properly.

2023-03-01 16:36 UTC, aronwk-aaron requested changes

2023-03-01 16:36 UTC, aronwk-aaron commented on dGame/dGameMessages/GameMessages.cpp
> +	bitStream.Write(armorRestore != 1);
should be != -1

2023-03-01 16:36 UTC, aronwk-aaron commented on dGame/dGameMessages/GameMessages.cpp
> +	bitStream.Write(healthRestore != 1);
should be != -1

2023-03-04 09:50 UTC, EmosewaMC commented
Imagination is properly reduced to half your current imagination, rounded to the nearest 10.
Visuals are correctly updated client side upon respawn.

2023-03-04 13:44 UTC, aronwk-aaron approved these changes

2023-03-05 19:11 UTC, Wincent01 approved these changes

2023-03-05 20:34 UTC, merged