fix compatibility with nexus dash
DarkflameUniverse/DarkflameServer pull request #1011
Opened 2023-03-04 06:11 UTC by aronwk-aaron

add some more utility to the masterserver -a command
fixes #1009

2023-03-04 06:56 UTC, Wincent01 requested changes
Would it be more intuitive to check for an existing user before taking the password?

Maybe this password change functionality should be limited to the operator user (GM=9). This would be to impose good practice, not have an admin change the passwords of the users for them. I've also thought about limiting the use of this command line option to only work for the first operator. There at least were some tutorials out there just after release which told folks to use -a to create accounts, which isn't what it should be used for.

2023-03-04 07:09 UTC, aronwk-aaron commented
> Would it be more intuitive to check for an existing user before taking the password?
> 
> Maybe this password change functionality should be limited to the operator user (GM=9). This would be to impose good practice, not have an admin change the passwords of the users for them. I've also thought about limiting the use of this command line option to only work for the first operator. There at least were some tutorials out there just after release which told folks to use -a to create accounts, which isn't what it should be used for.

Some good points. Not having to use a whole admin dashboard for a 1-2 player local server is kinda the biggest advocate for this being able to operate on multiple accounts, maybe only making a gm9 account if no other accounts exist, else make a GM 0 account.
But being able to reset any account's passwords is useful since I've seen people forget their passwords frequently. So having minimal account management tools in the server would be great for a single player or LAN server.

Taking in the password once at the beginning is just me being lazy and not duplicating more code, will fix

2023-03-04 07:38 UTC, aronwk-aaron commented
going to scope this down to just fixing compatibility with nexus dash, and improvements or locking down the -a command can be done separately

2023-03-04 07:40 UTC, Wincent01 approved these changes

2023-03-04 07:41 UTC, Wincent01 commented
The command doesn't have to be locked down. I can see it being useful for LAN setups as you say.

2023-03-04 09:53 UTC, EmosewaMC submitted a review, later dismissed

2023-03-04 09:53 UTC, EmosewaMC commented on dMasterServer/MasterServer.cpp
> +		}
This catch will output
```
error
account created successfully
```
Should probably move the success statement to below execute so it only gets output on a true success.

2023-03-05 01:23 UTC, EmosewaMC approved these changes

2023-03-05 19:11 UTC, Wincent01 approved these changes

2023-03-05 19:11 UTC, merged