Implement Timer handlers in triggers and ontimerdone trigger event
DarkflameUniverse/DarkflameServer pull request #1031
Opened 2023-03-27 00:59 UTC by aronwk-aaron

This PR implements the timer command handlers (settimer and canceltimer) as well as the ontimerdone event
Additionally, the AGJetEffect Server has been cleaned up and made 100% live accurate, which is the main reason for adding the timer trigger stuff since the beacons use them
Tested that it works properly and doesn't crash.

After delving into the triggers more, the Jeteffect is the only place it was used in Live, the rest are remnants from older versions of worlds

2023-03-27 01:01 UTC, aronwk-aaron commented
Note: this does NOT fix the cast skill of jet beacons. that is a separate issue with AOE that will be addressed in a separate PR

2023-03-27 08:41 UTC, EmosewaMC requested changes

2023-03-27 08:41 UTC, EmosewaMC commented on dGame/dComponents/SkillComponent.cpp
> -	context->skillID = skillID;
This needs to be kept.  It will break missions if this is removed here

2023-03-27 08:41 UTC, EmosewaMC commented on dGame/dComponents/SkillComponent.cpp
> +	context->skillID = skillId;
Keep this in though.  Since most of the time skillID was only needed for client casts I ignored setting it here.

2023-04-18 13:56 UTC, DarwinAnim8or approved these changes

2023-04-18 17:35 UTC, EmosewaMC approved these changes

2023-04-18 17:48 UTC, merged