fix: remove foreign key on name in cheat_detection table
DarkflameUniverse/DarkflameServer pull request #1202
Opened 2023-09-29 23:17 UTC by aronwk-aaron

Drop table incase it exists (which sometimes it doesn't) and then make it again without that foreign key
Tested on 10.11.5-MariaDB

2023-09-29 23:20 UTC, EmosewaMC requested changes
The old data needs to be moved over first.

2023-09-29 23:24 UTC, EmosewaMC commented
alternatively, we should instead just remove the foreign key by name.  this should be `player_cheat_detections_ibfk_1`

2023-09-29 23:26 UTC, EmosewaMC commented
```
ALTER TABLE player_cheat_detections DROP FOREIGN KEY `player_cheat_detections_ibfk_1`;
```
this should work instead.

2023-09-29 23:43 UTC, EmosewaMC approved these changes
Only suggested change is to add a comment saying why we are dropping a table in a sql query for future readers.

2023-09-30 06:25 UTC, Wincent01 approved these changes

2023-09-30 11:22 UTC, merged