feat: make make the help menu top 5 issues work and configurable
DarkflameUniverse/DarkflameServer pull request #1293
Opened 2023-11-14 07:10 UTC by aronwk-aaron

tested it, it just take html lol

![image](https://github.com/DarkflameUniverse/DarkflameServer/assets/26027722/1f698f20-c562-48ba-a7de-e3b5158efcd3)

2023-11-14 07:23 UTC, EmosewaMC commented on dCommon/dConfig.cpp
> +	auto key = line.substr(0, line.find('='));
Could optimize this to just do one search

2023-11-14 07:24 UTC, EmosewaMC commented on dNet/ClientPackets.cpp
> +	GameMessages::SendUIMessageServerToSingleClient(UserManager::Instance()->GetUser(sysAddr)->GetLastUsedChar()->GetEntity(), sysAddr, "UIHelpTop5", data);
Check for null on most of these pointers

2023-11-14 07:24 UTC, EmosewaMC commented on dWorldServer/WorldServer.cpp
> +		ClientPackets::SendTop5HelpIssues(packet->systemAddress, packet);
Packet isn't used in the function, can remove it from the api

2023-11-14 07:25 UTC, EmosewaMC commented on dWorldServer/WorldServer.cpp
> +		ClientPackets::SendTop5HelpIssues(packet->systemAddress, packet);
In that case just pass packet and read sysaddr when it is time

2023-11-14 14:10 UTC, BrieFlory requested changes

2023-11-14 14:10 UTC, BrieFlory commented on resources/worldconfig.ini
If I don't fix spelling and grammar mistakes it'll literally kill me

2023-11-14 14:10 UTC, BrieFlory commented on resources/worldconfig.ini
> +help_0_description=Go to the DarkflameServer repository on Github to view issues and discussions about the server emulator!<br/><br/><a href="https://github.com/DarkflameUniverse/DarkflameServer"><fo
GitHub

2023-11-14 14:10 UTC, BrieFlory commented on resources/worldconfig.ini
> +help_4_description=Visit Discussions on DarkflameServer to<br>ask questions and collaborate with other devs!<br/><br/>
Visit Discussions on the DarkflameServer GitHub page<br>to ask questions and collaborate with other devs!

2023-11-14 14:10 UTC, BrieFlory commented on resources/worldconfig.ini
> +help_2_description=Yep, while the server emulator is mostly complete, there are still some unimplemted parts that are being worked on. Such as property behaviors and Dragonmaw Chasm to name a couple.
unimplemented

Also, would change it to:

While DarkflameServer is a mostly complete emulator, there are still some features that aren't implemented. You can track these on the GitHub issues page.

2023-11-14 14:10 UTC, BrieFlory commented on resources/worldconfig.ini
> +help_1_description=Try switching networks or using your phone's hotspot to resolve the issue<br/><br/>
also suggest enabling a VPN?

2023-11-14 14:16 UTC, aronwk-aaron commented on resources/worldconfig.ini
lol

2023-11-14 14:17 UTC, aronwk-aaron commented on resources/worldconfig.ini
> +help_1_description=Try switching networks or using your phone's hotspot to resolve the issue<br/><br/>
true

2023-11-14 19:16 UTC, EmosewaMC approved these changes

2023-11-14 19:16 UTC, EmosewaMC commented on resources/worldconfig.ini
> +help_4_description=Visit Discussions on the DarkflameServer GitHub page<br/>to ask questions and collaborate with other devs!<br/><br/>
Newline

2023-11-14 23:38 UTC, EmosewaMC approved these changes

2023-11-16 01:30 UTC, Jettford approved these changes

2023-11-16 01:30 UTC, merged