feat: Add config update function
DarkflameUniverse/DarkflameServer pull request #1379
Opened 2024-01-02 01:58 UTC by EmosewaMC

Appends a new option to the specified file which contains the same contents as the old option, but with the updated name specified in the high level cmake.

Tested that I can run the cmake multiple times and a singular extra config option is generated with the same value as was in the previous option.

2024-01-02 02:00 UTC, aronwk-aaron submitted a review, later dismissed

2024-01-02 02:01 UTC, Jettford requested changes
This should be in a .cmake file as a utility.

2024-01-02 02:33 UTC, EmosewaMC commented
there are you happy cmake

2024-01-02 03:51 UTC, aronwk-aaron submitted a review, later dismissed

2024-01-02 07:27 UTC, Xiphoseer approved these changes

2024-01-02 08:25 UTC, Jettford submitted a review, later dismissed

2024-01-02 15:40 UTC, aronwk-aaron approved these changes

2024-01-03 00:21 UTC, Xiphoseer approved these changes

2024-01-03 00:25 UTC, merged