fix: missing stack trace function definitions
DarkflameUniverse/DarkflameServer pull request #1507
Opened 2024-03-25 04:53 UTC by EmosewaMC

fixes an issue where the stack traces no longer had any information.  The space savings came from not having the information there which is necessary for stack traces.

2024-03-25 04:57 UTC, aronwk-aaron approved these changes

2024-03-26 11:34 UTC, jadebenn commented
I think this is using a hammer instead of a scapel. There should be a way to generate the symbols we need for traces without generating symbols for every single function (including templates and inlines) by not suppressing symbol visibility. Also, MSVC defaults to hidden symbols, so if this is an issue, this isn't a portable solution.

One question I have as well is whether we intend for stack traces to be accessible outside debug builds. If we do, then fixing this makes sense. If not, then I think it might make more sense to just use a debug configuration for development.

2024-03-26 11:35 UTC, jadebenn requested changes
I think this is using a hammer instead of a scapel. There should be a way to generate the symbols we need for traces without generating symbols for every single function (including templates and inlines) by not suppressing symbol visibility. Also, MSVC defaults to hidden symbols, so if this is an issue, this isn't a portable solution.

One question I have as well is whether we intend for stack traces to be accessible outside debug builds. If we do, then fixing this makes sense. If not, then I think it might make more sense to just use a debug configuration for development.

2024-03-26 11:39 UTC, jadebenn commented
One thing I would try prior to this is explicitly enabling debug symbol generation with -g. I _think_ that should restore stack traces while minimizing bloat to the library.

2024-03-26 12:43 UTC, EmosewaMC commented
the previous change broke stack trace info and is preventing stack traces on non-msvc crashes.  If you want the optimziation then you can look into it, but i will not be and just want working stack traces and the small binary size increase is insignficant when compared to a functional feature.

2024-03-26 13:08 UTC, jadebenn commented
I strongly disagree that the solution here is to just rip out the change. When we encounter other bugs, we don't just rip out the offending function without attempting to solve the issue.

There are a few questions I have:

1. Since we already know that the code isn't portable, do we need this in release builds? If not, why is the solution here removal?
2. Have you tried setting the visibility to hidden-inline as an interim measure?
3. Have you tried generating debug symbols?

2024-03-26 21:50 UTC, EmosewaMC commented
> I strongly disagree that the solution here is to just rip out the change. When we encounter other bugs, we don't just rip out the offending function without attempting to solve the issue.
> 
> There are a few questions I have:
> 
> 1. Since we already know that the code isn't portable, do we need this in release builds? If not, why is the solution here removal?
> 2. Have you tried setting the visibility to hidden-inline as an interim measure?
> 3. Have you tried generating debug symbols?

No, no and no because I don't want to work in cmake.  Last time i broke something the code was reverted without giving me time to look at the issue to give the person with more knowledge on the feature time to work on it

2024-03-26 22:19 UTC, closed without merging

2024-03-27 02:09 UTC, jadebenn commented
Sorry things got heated earlier. I've got a fix going up now that partially rolls back the change I made, and I've tested that it restores trace functionality.