Fix issue #268 : wrong shirt colors in the character selection
DarkflameUniverse/DarkflameServer pull request #293
Opened 2021-12-22 15:07 UTC by Racater

This pull request fixes the issue #268 .
Now the characters will get the correct shirt color for shirts such as the space suit in the character creation menu (dark green and medium blue).
Has been tested locally.

2021-12-22 21:46 UTC, averysumner commented
Looks good to me.

2021-12-24 03:21 UTC, Jettford commented
Maybe this should be replaced with a CDClient query such as this implementation of it. https://github.com/UchuServer/Uchu/blob/92894ace6f0f83ff1c9725b2bde58dfa4e883481/Uchu.Char/Handlers/CharacterHandler.cs#L97-L110

2021-12-26 13:49 UTC, DarwinAnim8or approved these changes

2021-12-26 13:53 UTC, DarwinAnim8or commented
@Racater hadn't seen your latest commit before reviewing, have you tested this works?

2021-12-26 13:55 UTC, Racater commented
@Jettford following your comment, I rewrote and simplified the code for the shirt at character creation. This way we remove this list of hardcoded values.

2021-12-26 13:56 UTC, Racater commented
This has been tested to work on my local server with all edge cases I could think of (first shirt style, last shirt style, different colors, etc.)

2021-12-28 08:58 UTC, MickVermeulen requested changes
Have some code style comments.

2021-12-28 08:58 UTC, MickVermeulen commented on dGame/UserManager.cpp
> +uint32_t getShirtColorId(uint32_t color) {
This should be CamelCase

2021-12-28 08:58 UTC, MickVermeulen commented on dGame/UserManager.cpp
> +	auto colorId = std::find (shirtColorVector.begin(), shirtColorVector.end(), color);
`std::find (` should be `std::find(`

2021-12-28 18:57 UTC, Racater commented on dGame/UserManager.cpp
> +uint32_t getShirtColorId(uint32_t color) {
done

2021-12-28 18:57 UTC, Racater commented on dGame/UserManager.cpp
> +	auto colorId = std::find (shirtColorVector.begin(), shirtColorVector.end(), color);
fixed

2022-01-03 17:44 UTC, MickVermeulen approved these changes
Yeah LGTM, @DarwinAnim8or you assigned yourself for review, do you still plan on doing that or was it a misclick (given that you already approved before :P)

2022-01-11 22:48 UTC, DarwinAnim8or approved these changes

2022-01-11 22:48 UTC, merged