Fix UserManager not logging chosen name properly
DarkflameUniverse/DarkflameServer pull request #415
Opened 2022-01-25 00:33 UTC by Marcono1234

Previously when the user chose a predefined name, the logging call would simply log an empty string because `name` is empty and their name was only stored in `predefinedName`.

2022-01-25 14:35 UTC, DarwinAnim8or requested changes
I think this would be a good oppertunity to change that log message to just log both (if a to be moderated name is entered)

2022-01-29 23:13 UTC, Marcono1234 commented
A few lines above it is already logging "Got predefined name: %s\n". Should I remove that and combine it in the modified logging call here? E.g.:
```cpp
if (name == "") {
  Game::logger->Log("UserManager", "AccountID: %i is creating a character with predefined name: %s\n", u->GetAccountID(), predefinedName.c_str());
} else {
  Game::logger->Log("UserManager", "AccountID: %i is creating a character with name: %s (temporary: %s)\n", u->GetAccountID(), name.c_str(), predefinedName.c_str());
}
```

2022-01-31 12:35 UTC, averysumner commented
> A few lines above it is already logging "Got predefined name: %s\n". Should I remove that and combine it in the modified logging call here? E.g.:
> 
> ```c++
> if (name == "") {
>   Game::logger->Log("UserManager", "AccountID: %i is creating a character with predefined name: %s\n", u->GetAccountID(), predefinedName.c_str());
> } else {
>   Game::logger->Log("UserManager", "AccountID: %i is creating a character with name: %s (temporary: %s)\n", u->GetAccountID(), name.c_str(), predefinedName.c_str());
> }
> ```

Go for it.

2022-04-03 09:19 UTC, EmosewaMC approved these changes
This looks good to me.  @averysumner @DarwinAnim8or If this looks good to you two let's get this merged

2022-04-03 09:21 UTC, DarwinAnim8or approved these changes
Ah, thanks for bumping this, had forgotten about it. Looks good

2022-04-03 09:33 UTC, merged