Added more specific bug reporting
DarkflameUniverse/DarkflameServer pull request #476
Opened 2022-03-24 08:16 UTC by EmosewaMC

Made bug reporting more specific by adding a reporter_id column that contains the characterID of the reporting player.  Added a migration to add the column to the existing bug_reports table.  Also changed the stored OtherPlayerID from the LWOOBJID to the characterID.

Tested changed by reporting general bugs through the drop down and reporting other players and had no exceptions and bugs were reported correctly.

2022-03-30 21:58 UTC, aronwk-aaron commented
bump so I know when i need to make changes to Nexus Dashboard for this

2022-03-31 09:29 UTC, DarwinAnim8or requested changes
// Convert other player id from LWOOBJID to the database id.

This can be done a lot simpler, you can simply chop off the bits you dont need by casting to a uint32_t

Something like this might be enough: 
```
LWOOBJID otherPlayer = LWOOBJID_INVALID;
if (nOtherPlayerID != "") otherPlayer = std::atoi(nOtherPlayerID);
```

2022-03-31 09:47 UTC, EmosewaMC commented
> // Convert other player id from LWOOBJID to the database id.
> 
> This can be done a lot simpler, you can simply chop off the bits you dont need by casting to a uint32_t
> 
> Something like this might be enough:
> 
> ```
> LWOOBJID otherPlayer = LWOOBJID_INVALID;
> if (nOtherPlayerID != "") otherPlayer = std::atoi(nOtherPlayerID);
> ```

oh really?  I had assumed we use bit 30 for the character but after looking at the bits we set, they are 32 and 60.  Ill make those changes happily and note this for the future.

2022-03-31 10:21 UTC, EmosewaMC commented
simplified the conversion and added a e.what() on the off chance an error happens.  lmk if this looks good

2022-04-01 22:12 UTC, EmosewaMC commented
Since i made the requested change @DarwinAnim8or im gonna go ahead and merge this.

2022-04-01 22:12 UTC, merged