Implement flying command
DarkflameUniverse/DarkflameServer pull request #713
Opened 2022-08-05 08:14 UTC by Jettford

2022-08-05 12:43 UTC, aronwk-aaron requested changes
Only other thing to note is that docs need to be updated as well

2022-08-05 12:43 UTC, aronwk-aaron commented on dGame/Character.h
> +    void SetIsFlying(bool isFlying) { m_IsFlying = isFlying; }
change spaces to tabs, please

2022-08-05 17:59 UTC, aronwk-aaron approved these changes

2022-08-05 18:30 UTC, EmosewaMC commented
What tests have you done for this?

2022-08-06 05:42 UTC, Jettford commented
Tests? This adds a command that allows GMs to fly without Jetpacks.

2022-08-06 06:16 UTC, EmosewaMC commented
How have you tested this functionality?  What edge cases have been checked
to ensure this doesn't break any current functionality?

On Fri, Aug 5, 2022, 10:42 PM Jett ***@***.***> wrote:

> Tests? This adds a command that allows GMs to fly without Jetpacks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DarkflameUniverse/DarkflameServer/pull/713#issuecomment-1207153057>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQ67BJFHKD2O6VVO2NWTR3VXX3MPANCNFSM55VG256Q>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-08-06 06:49 UTC, Jettford commented
Of course I have tested the functionality and tested that it doesn't break anything existing.

2022-08-06 07:18 UTC, EmosewaMC commented
> Of course I have tested the functionality and tested that it doesn't break anything existing.

Just wanted to make sure we had some written log of what was tested for the future - looks reasonable to me

2022-08-06 08:19 UTC, merged