Remove Locale
DarkflameUniverse/DarkflameServer pull request #808
Opened 2022-11-02 07:22 UTC by EmosewaMC

Untested but should be correct.

If someone wants to prop a build and test this before tomorrow feel free to otherwise **this will be tested tomorrow**.

2022-11-03 03:37 UTC, EmosewaMC commented
This has been tested and works

2022-11-03 03:53 UTC, aronwk-aaron submitted a review, later dismissed

2022-11-10 19:12 UTC, aronwk-aaron approved these changes
re-approving since I fixed merge conflicts

2022-11-12 09:06 UTC, Jettford approved these changes

2022-11-12 14:45 UTC, aronwk-aaron requested changes
Please fix failing CI

2022-11-12 20:29 UTC, aronwk-aaron approved these changes

2022-11-27 16:33 UTC, Jettford approved these changes

2022-11-27 21:41 UTC, Wincent01 submitted a review, later dismissed

2022-11-28 00:39 UTC, aronwk-aaron approved these changes

2022-11-28 00:56 UTC, Jettford approved these changes

2022-11-28 00:56 UTC, merged