breakout gmlevel enum and make it a class
DarkflameUniverse/DarkflameServer pull request #996
Opened 2023-02-19 21:00 UTC by aronwk-aaron

tested that things still work
slash command,
chat restrictions,
packets and serializations

2023-02-24 09:22 UTC, EmosewaMC requested changes

2023-02-24 09:22 UTC, EmosewaMC commented on dGame/dUtilities/SlashCommandHandler.cpp
> +	if (chatCommand == "spawnphysicsverts" && entity->GetGMLevel() >= eGameMasterLevel::LEAD_MODERATOR) {
This is off by one - the current version is compared with 6 which is junior developer

2023-02-24 09:22 UTC, EmosewaMC commented on dGame/dUtilities/SlashCommandHandler.cpp
> +	if (chatCommand == "reportproxphys" && entity->GetGMLevel() >= eGameMasterLevel::LEAD_MODERATOR) {
same here

2023-02-25 00:52 UTC, EmosewaMC approved these changes

2023-03-22 01:16 UTC, EmosewaMC approved these changes
lgtm

2023-03-23 21:06 UTC, EmosewaMC approved these changes

2023-03-24 22:07 UTC, Jettford approved these changes

2023-03-24 23:16 UTC, merged